
// curve_checks.h - elliptic curve unit tests
//
//    These constants were generated from the Mina c-reference-signer
//    Do not edit this file

#pragma once

#include "crypto.h"

#define EPOCHS 5

// Test scalars
static const Scalar S[5][2] = {
    {
        { 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, },
        { 0x15e789b5c213f2a4, 0x3f529d13f93f3c41, 0xd2543e425ecf2414, 0x3fac61733b4de912, },
    },
    {
        { 0x50b5ec5a60ddc229, 0x42fe744d4cc75e2c, 0x18edf4d0dc389cdf, 0x2538b8bb7d9b4f5f, },
        { 0xa57d55f98868293b, 0x7c801d22c1a45a42, 0x980e39a6b18cf97b, 0x16d7b2d4672d4b10, },
    },
    {
        { 0x0d3e44d76cb73b46, 0x12e178d31ad61de7, 0x7db1bc636d9ad238, 0x3fc6b711aa4a1fab, },
        { 0x5900f79758db403d, 0xd24ecae9c0cbee08, 0x0c5955d1190bbed5, 0x24fdaa02e2a26b06, },
    },
    {
        { 0x4dcc61570bf0b56a, 0xff75263a48fcfd74, 0x59c3dd208df2c20f, 0x3a69cdf4bca0d0b3, },
        { 0x09dbb238f5d36cd2, 0x6d70d3eef0dfaa7a, 0x72fa59b2efae9a4b, 0x1ac97f027d690a5d, },
    },
    {
        { 0x3327efd3f45f5685, 0x679a53fb263e608c, 0x856d5423c9b3b05a, 0x0bf8543515fdf896, },
        { 0xaae8848a9ec725d0, 0xba85ab82a785198e, 0xedd1b5c391b9038b, 0x2d0f9e2e08237981, },
    },
};

// Test curve points
static const Affine A[5][3] = {
    {
        {
            { 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,  },
            { 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,  },
        },
        {
            { 0xd54b82d77c6c897d, 0x341849985612cbfa, 0x3bbb1b3192d6a550, 0x159eda31e611c24c,  },
            { 0x1575e23de5c5e9ce, 0xc078a0b274ada00c, 0xfd84ff6103a107ee, 0x16a9a30a7157569f,  },
        },
        {
            { 0xb9a14146ed39c44e, 0x17aa4419bdd55b6d, 0x55729f57939d5c12, 0x1ae7f09b8f1a4945,  },
            { 0x12517e29766677fb, 0x3c61428e61f8d94f, 0x36745eec01931a67, 0x06de5932dabfdb72,  },
        },
    },
    {
        {
            { 0x45d62f535ded5b98, 0xd3dfb2db07ef4502, 0x7a613e3bbe4272e0, 0x1eff2648f0e01726,  },
            { 0x4d36d0f5954eca83, 0x05e88e22a88c1466, 0x67a0de5d4feb1998, 0x124e81009f45ce2d,  },
        },
        {
            { 0xdf578bd49c679ea1, 0xf784dbd80ef2ea06, 0x919a6421fd632a11, 0x2708dea778dddfd8,  },
            { 0x6e8b4353ae676b86, 0x4bf088e52bff5c84, 0xb98bb691ce1edd96, 0x0417b14095ea2b2a,  },
        },
        {
            { 0x446b85bcc6ad689b, 0xe219ecc9f30294c3, 0x1b0a96306e3f5f26, 0x2b93579f4d355692,  },
            { 0xc5885124d0f36a94, 0x190fb89cc49e20ab, 0xf8316144f8882b6f, 0x2220a07f479465e7,  },
        },
    },
    {
        {
            { 0xc812f574a0e4e7cb, 0x5de57084c31f2d5a, 0x4daec9d740c31cf2, 0x24ca918d8d26ca6a,  },
            { 0x473c24c5ecfe4afd, 0x0ebc242458a71c30, 0x69a738855307bf11, 0x11b8ec28da46deef,  },
        },
        {
            { 0xaebfe43d3ae5b825, 0xd260817025fab5ba, 0x4b0a09b388907ead, 0x041a96ed752fc784,  },
            { 0xa472eb8887d0fb52, 0x1a7951ff27e9bd6f, 0x3e01d2b51cdf0b14, 0x0d2db9688992afeb,  },
        },
        {
            { 0x74d97ee183bf837d, 0xde37ca4bfc67588c, 0xe29417fb517ce7b6, 0x292e9a18c2a14ce0,  },
            { 0x1620c95bdbc45995, 0x8a3cd05cb0840dc7, 0xf0e0dba874c902e8, 0x1bd02ad10d3ad858,  },
        },
    },
    {
        {
            { 0xbd3c7224c5038313, 0x9786eb7e009341b7, 0x343c69d2d1e29e88, 0x324ebaa7006d73f9,  },
            { 0xac28e895d9e4ae14, 0x98444f7bb83580cc, 0x6e937b98cb4cf9b7, 0x3d6d348d771d862a,  },
        },
        {
            { 0x4723ec9e4e2bf2d9, 0xc315d6c516e89b1b, 0x0bb28b2201114f47, 0x1c208470fa6cd8ff,  },
            { 0xa37ca87f0e32c76c, 0xb5a7b6a3cda16e4b, 0x14ec13825d90193e, 0x06e35deead4f4f93,  },
        },
        {
            { 0xb7932b70cf5893ab, 0x122781eda3734d7e, 0xff8603ca682d3d2c, 0x02511828b168e67b,  },
            { 0x73533ca8dce433b5, 0xb80e0af34d975c62, 0x1c1793207b619353, 0x1e8875d2ff0a09de,  },
        },